version: "3"

services:
  mysql-01:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d:ro
      - ./charset.cnf:/etc/mysql/conf.d/charset.cnf
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eiQOvkadszivfdfskl
      TZ: Asia/Seoul
    platform: linux/amd64

  mysql-test:
    image: mysql:5.7
    volumes:
      - ./data-test:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d:ro
      - ./charset.cnf:/etc/mysql/conf.d/charset.cnf
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: af3das0faj1afkal
      TZ: Asia/Seoul
    platform: linux/amd64